version: '3'

services:
  tuleap:
    build: tuleap
    ports:
      - 80:80
      - 443:443
      - 22:22
    environment:
      - VIRTUAL_HOST=54.156.3.127
      - ROOT_PWD=admin
      - SITEADMIN_PWD=siteadmin
