version: '3'

services:
  tuleap:
    build: tuleap
    ports:
      - 80:80
      - 443:443
      - 22:22
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:-localhost}
      - ROOT_PWD=${ADMIN_PWD:-projectoradmin}
      - SITEADMIN_PWD=${ADMIN_PWD:-projectoradmin}
